language: r
sudo : false
warnings_are_errors: false
cache: packages
before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh

install:
  - ./travis-tool.sh github_package jason-p-pickering/openxlsx
  - ./travis-tool.sh install_deps
